name: Prettier

on:
  - push
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/cache-and-install-pnpm
      - name: Prettier
        run: pnpm prettier:check
