name: Prettier

on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache-and-install@v1
      - name: Prettier
        run: pnpm prettier:check
