name: Prettier

on:
  - push
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-pnpm.yaml
      - name: Prettier
        run: pnpm prettier:check
